### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Richthofen1** [clbhundley/Free-Cities-Godot#3]
Hi there, i appreciate the effort, but i cannot make this game run. your instructions assume a high level skill to figure out. I managed to clone the folder to the same folder on my disk where this godot engine is. I scan everywhere but it will not find a project. 
![unbenannt](https://user-images.githubusercontent.com/43900961/46568030-dac06f80-c93e-11e8-8e61-4ea05622280a.JPG)

**Comment by clbhundley** [comment]
Thank you for bringing this to my attention.
I've rewritten the setup instructions to be more clear and easier to follow:
https://github.com/clbhundley/Free-Cities-Godot/wiki/Setup-Instructions
